import type { User } from '@/lib/userTypes'

export const USER_SEED_DATA: User[] = [
  {
    id: 'u-1',
    username: 'kasun.s',
    email: 'kasun.s@excise.gov.lk',
    firstName: 'Kasun',
    lastName: 'Silva',
    roles: ['SUPER_ADMIN'],
    status: 'ACTIVE',
    nic: '198512345678',
    phone: '0712345678',
    department: 'IT',
  },
  {
    id: 'u-2',
    username: 'chamara.p',
    email: 'chamara.p@excise.gov.lk',
    firstName: 'Chamara',
    lastName: 'Perera',
    roles: ['EXCISE_OFFICER'],
    status: 'ACTIVE',
    nic: '881234567V',
    phone: '0771234567',
    department: 'Operations',
    stationCode: 'CMB-01',
  },
  {
    id: 'u-3',
    username: 'nuwan.w',
    email: 'nuwan.w@excise.gov.lk',
    firstName: 'Nuwan',
    lastName: 'Wijesinghe',
    roles: ['DATA_ENTRY_OPERATOR'],
    status: 'ACTIVE',
    nic: '921234567V',
    department: 'Licensing',
  },
  {
    id: 'u-4',
    username: 'amali.f',
    email: 'amali.f@excise.gov.lk',
    firstName: 'Amali',
    lastName: 'Fernando',
    roles: ['AUDITOR'],
    status: 'INACTIVE',
    nic: '199012345678',
    department: 'Audit',
  },
  {
    id: 'u-5',
    username: 'tharindu.j',
    email: 'tharindu.j@excise.gov.lk',
    firstName: 'Tharindu',
    lastName: 'Jayasinghe',
    roles: ['EXCISE_OFFICER'],
    status: 'PENDING',
    phone: '0751122334',
    department: 'Licensing',
    stationCode: 'GAL-02',
  },
]
